### ISSUE TITLE
Need to make metadata long 

### ISSUE THREAD

**Issue by amyerspigg** [COMPASS-DOE/ec1-tai-geochemistry#5]
https://github.com/COMPASS-DOE/ec1-tai-geochemistry/blob/12dbf3a37810315d9875876e7cc0cf4c69c221cd/ec1-tai-geochemistry-loading-data.Rmd#L112

**Comment by stephpenn1** [comment]
Done and replaced in submission folder, wide version moved to `MAYBE DON'T NEED` folder.

New df looks like this:

![Screen Shot 2023-03-13 at 10 02 24 AM](https://user-images.githubusercontent.com/20341158/224724558-deb5fa34-6548-4904-b185-bda364d01769.png)

**Comment by stephpenn1** [comment]
For future reference this was the pivot code

```
metadata_collected_wide %>% 
  mutate(across(everything(), as.character)) %>% 
  pivot_longer(cols = -c("kit_id", "elevation_flag"), 
               names_to = c("transect_location", ".value"),
               names_pattern = "^([^_]+)_(.*)",
               values_to = ".value") -> metadata_collected_long
